# Generated by Django 5.2 on 2025-04-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street_No', models.CharField(max_length=10)),
                ('Street', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=20)),
                ('Zip', models.CharField(max_length=10)),
                ('Type', models.CharField(max_length=50)),
                ('OwnerID', models.IntegerField()),
                ('OwnerType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('DoB', models.DateField()),
                ('Gender', models.CharField(max_length=20)),
                ('ResidencyState', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
                ('Applicant_Relationship', models.CharField(max_length=50)),
            ],
        ),
    ]
